name: update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          EMAIL: ${{ secrets.EMAIL }}
      - run: bash script.sh
